### ISSUE TITLE
Reg.  hardness

### ISSUE THREAD

**Issue by shahramyalameha** [hitliaomq/ElasticPOST#1]
Hi,
How is the equation related to the hardness calculated or based on what reference is it calculated?
Line 24 of ### Hardness.m file:
 H = 0.130548175274347*E.^(2.2484942942017).*B.^(-1.51675853808829);
Thanks.

**Comment by hitliaomq** [comment]
This equation is fitted by myself, and which has not been published yet.
If you like, you can set use the 'c' or 't' as the hardness model by changing the source code. The reference for 'c' and 't' are listed as follows:
'c': https://doi.org/10.1016/j.intermet.2011.03.026
't': https://doi.org/10.1016/j.ijrmhm.2012.02.021

**Comment by shahramyalameha** [comment]
Thanks for your reply.
How can I cite the hardness that you fitted? Are these two references sufficient?

**Comment by hitliaomq** [comment]
@shahramyalameha Thank you for your interest on this model. 
If you used it, please cite this code(ElasticPOST) and give the link(https://github.com/hitliaomq/ElasticPOST) of this code.
