### ISSUE TITLE
How to change the range of colorbar

### ISSUE THREAD

**Issue by qingtianya-wyt** [hitliaomq/ElasticPOST#2]
Hi，I want to change the range of colorbar. Howerver, there is only one mode named auto. If I changed the default range , the colorbar will disappear, is there any ways to change this situation? And the  colorbar is also too large which is unmatch to the whole fig. Could you make some adjustments?  Thanks for your code.

**Comment by hitliaomq** [comment]
@qingtianya-wyt Using 'm' to replace the 'auto', and then change the color range. If you can  speak Chinese, the following tutorial may be useful. As for 'the colorbar is too large', I have no ideal.
https://www.bilibili.com/video/BV1ne411P7gB

**Comment by qingtianya-wyt** [comment]
Thanks for your reply, I have watched your video and changed the range of colorbar successfully.
